name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ New features"
    labels: ["type: enhancement"]
  - title: "🐛 Bug Fixes"
    labels: ["type: bug"]
  - title: "🛠️ Maintenance"
    labels: ["type: build"]

# We will include only the categorized pull requests to the release notes
include-labels: ["type: enhancement", "type: bug", "type: build"]

change-template: "- $TITLE _(PR #$NUMBER, by @$AUTHOR)_."
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  default: patch

  major:
    labels: []
  minor:
    labels: ["type: enhancement"] # New features will usually mean a new minor release
  patch:
    labels: []

template: |
  $CHANGES
