name: Flutter checks

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate translations
        run: dart run slang

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
